#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define MAX_COUNTRY_NAME_LEN (50 + 1)
#define MAX_COUNTRY_CAPITAL_LEN (50 + 1)
#define MAX_COUNTRY_CONTINENT_LEN (50 + 1)

#define MAX_COUNTRIES 1000

#endif // CONSTANTS_H_
